# Generated by Django 4.1.4 on 2022-12-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_equipment_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotesDto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipment",
            name="data_entrada",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="data_entrega",
            field=models.DateTimeField(null=True),
        ),
    ]
