# Generated by Django 4.1.4 on 2022-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_notesdto_equipment_data_entrada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="data_entrada",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="data_entrega",
            field=models.DateField(null=True),
        ),
    ]
